INFO 2024-03-26 16:36:41,406 autoreload 5680 10404 Watching for file changes with StatReloader
INFO 2024-03-26 16:36:45,847 basehttp 5680 19972 "GET /second/random_num/ HTTP/1.1" 200 2
INFO 2024-03-26 16:36:47,850 basehttp 5680 19972 "GET /second/random_num/ HTTP/1.1" 200 1
INFO 2024-03-26 16:36:51,527 basehttp 5680 19972 "GET /second/random_num/ HTTP/1.1" 200 2
INFO 2024-03-26 16:38:36,411 autoreload 5680 10404 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\birukovproject\settings.py changed, reloading.
INFO 2024-03-26 16:38:40,905 basehttp 19140 23384 "GET /second/random_num/ HTTP/1.1" 200 2 <socket.socket fd=1180, family=2, type=1, proto=0, laddr=('127.0.0.1', 8080), raddr=('127.0.0.1', 62558)>
INFO 2024-03-26 16:39:03,545 basehttp 19140 23384 "GET /second/random_num/ HTTP/1.1" 200 2 <socket.socket fd=1180, family=2, type=1, proto=0, laddr=('127.0.0.1', 8080), raddr=('127.0.0.1', 62558)>
INFO 2024-03-26 16:39:55,121 autoreload 10640 10860 Watching for file changes with StatReloader
INFO 2024-03-26 16:39:58,407 basehttp 10640 23116 "GET /second/random_num/ HTTP/1.1" 200 2
WARNING 2024-03-26 16:40:56,309 log 10640 3520 Not Found: /favicon.ico
WARNING 2024-03-26 16:40:56,309 basehttp 10640 3520 "GET /favicon.ico HTTP/1.1" 404 2553
INFO 2024-03-26 16:48:57,600 autoreload 10640 10860 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-26 16:48:57,911 autoreload 19316 11988 Watching for file changes with StatReloader
INFO 2024-03-26 16:49:15,363 autoreload 19316 11988 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-26 16:49:15,661 autoreload 1360 13624 Watching for file changes with StatReloader
INFO 2024-03-26 16:49:44,289 autoreload 1360 13624 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-26 16:49:44,589 autoreload 12824 2716 Watching for file changes with StatReloader
INFO 2024-03-26 16:50:11,151 autoreload 12824 2716 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-26 16:50:11,452 autoreload 11304 1544 Watching for file changes with StatReloader
INFO 2024-03-26 16:50:22,355 views 11304 20988 Орёл
INFO 2024-03-26 16:50:22,356 basehttp 11304 20988 "GET /second/coin/ HTTP/1.1" 200 8
INFO 2024-03-26 16:50:59,455 autoreload 11304 1544 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-26 16:50:59,760 autoreload 20444 22984 Watching for file changes with StatReloader
INFO 2024-03-26 16:51:42,598 autoreload 20444 22984 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-26 16:51:42,896 autoreload 15880 20112 Watching for file changes with StatReloader
INFO 2024-03-26 16:52:23,720 autoreload 15880 20112 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-26 16:52:24,030 autoreload 2016 884 Watching for file changes with StatReloader
INFO 2024-03-26 16:52:25,542 views 2016 10740 Выпало: Решка
INFO 2024-03-26 16:52:25,542 basehttp 2016 10740 "GET /second/coin/ HTTP/1.1" 200 24
INFO 2024-03-26 16:54:27,175 autoreload 2016 884 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-26 16:54:27,476 autoreload 11356 8184 Watching for file changes with StatReloader
INFO 2024-03-26 16:54:29,480 views 11356 992 После броска моентки выпало: Решка
INFO 2024-03-26 16:54:29,480 basehttp 11356 992 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-26 16:54:36,087 views 11356 992 После броска кубика выпало: 5
INFO 2024-03-26 16:54:36,088 basehttp 11356 992 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:54:38,544 views 11356 992 После броска кубика выпало: 4
INFO 2024-03-26 16:54:38,545 basehttp 11356 992 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:54:39,316 views 11356 992 После броска кубика выпало: 4
INFO 2024-03-26 16:54:39,317 basehttp 11356 992 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:54:40,591 views 11356 992 После броска кубика выпало: 5
INFO 2024-03-26 16:54:40,592 basehttp 11356 992 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:54:41,185 views 11356 992 После броска кубика выпало: 1
INFO 2024-03-26 16:54:41,185 basehttp 11356 992 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:54:41,757 views 11356 992 После броска кубика выпало: 7
INFO 2024-03-26 16:54:41,757 basehttp 11356 992 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:54:42,289 views 11356 992 После броска кубика выпало: 7
INFO 2024-03-26 16:54:42,289 basehttp 11356 992 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:54:51,477 views 11356 992 После броска кубика выпало: 7
INFO 2024-03-26 16:54:51,478 basehttp 11356 992 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:54:52,141 autoreload 11356 8184 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-26 16:54:52,453 autoreload 13784 10344 Watching for file changes with StatReloader
INFO 2024-03-26 16:54:53,390 views 13784 4568 После броска кубика выпало: 3
INFO 2024-03-26 16:54:53,391 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:54:55,562 views 13784 4568 После броска кубика выпало: 1
INFO 2024-03-26 16:54:55,562 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:55:11,601 views 13784 4568 Случайное число: 14
INFO 2024-03-26 16:55:11,601 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:55:13,472 views 13784 4568 Случайное число: 10
INFO 2024-03-26 16:55:13,472 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:55:14,703 views 13784 4568 Случайное число: 79
INFO 2024-03-26 16:55:14,703 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:55:15,285 views 13784 4568 Случайное число: 23
INFO 2024-03-26 16:55:15,286 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:55:15,712 views 13784 4568 Случайное число: 11
INFO 2024-03-26 16:55:15,713 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:05,066 views 13784 4568 Случайное число: 37
INFO 2024-03-26 16:56:05,066 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:06,061 views 13784 4568 Случайное число: 84
INFO 2024-03-26 16:56:06,061 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:06,709 views 13784 4568 Случайное число: 98
INFO 2024-03-26 16:56:06,709 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:07,162 views 13784 4568 Случайное число: 47
INFO 2024-03-26 16:56:07,163 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:07,478 views 13784 4568 Случайное число: 1
INFO 2024-03-26 16:56:07,478 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 41
INFO 2024-03-26 16:56:07,923 views 13784 4568 Случайное число: 83
INFO 2024-03-26 16:56:07,923 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:08,790 views 13784 4568 Случайное число: 63
INFO 2024-03-26 16:56:08,791 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:09,243 views 13784 4568 Случайное число: 81
INFO 2024-03-26 16:56:09,244 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:09,472 views 13784 4568 Случайное число: 99
INFO 2024-03-26 16:56:09,473 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:09,687 views 13784 4568 Случайное число: 45
INFO 2024-03-26 16:56:09,687 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:09,865 views 13784 4568 Случайное число: 89
INFO 2024-03-26 16:56:09,866 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:10,071 views 13784 4568 Случайное число: 4
INFO 2024-03-26 16:56:10,071 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 41
INFO 2024-03-26 16:56:10,279 views 13784 4568 Случайное число: 76
INFO 2024-03-26 16:56:10,279 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:10,788 views 13784 4568 Случайное число: 83
INFO 2024-03-26 16:56:10,788 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:10,986 views 13784 4568 Случайное число: 4
INFO 2024-03-26 16:56:10,986 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 41
INFO 2024-03-26 16:56:11,172 views 13784 4568 Случайное число: 89
INFO 2024-03-26 16:56:11,172 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:11,349 views 13784 4568 Случайное число: 71
INFO 2024-03-26 16:56:11,349 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:11,665 views 13784 4568 Случайное число: 5
INFO 2024-03-26 16:56:11,666 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 41
INFO 2024-03-26 16:56:11,854 views 13784 4568 Случайное число: 17
INFO 2024-03-26 16:56:11,854 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:56:12,040 views 13784 4568 Случайное число: 63
INFO 2024-03-26 16:56:12,041 basehttp 13784 4568 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 16:58:31,514 basehttp 13784 4568 "GET / HTTP/1.1" 200 27
INFO 2024-03-26 16:58:50,305 views 13784 4568 После броска моентки выпало: Решка
INFO 2024-03-26 16:58:50,305 basehttp 13784 4568 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-26 16:58:53,943 views 13784 4568 После броска моентки выпало: Орёл
INFO 2024-03-26 16:58:53,943 basehttp 13784 4568 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-26 16:58:55,663 views 13784 4568 После броска моентки выпало: Орёл
INFO 2024-03-26 16:58:55,664 basehttp 13784 4568 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-26 16:58:57,591 views 13784 4568 После броска моентки выпало: Решка
INFO 2024-03-26 16:58:57,591 basehttp 13784 4568 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-26 16:59:01,997 views 13784 4568 После броска моентки выпало: Решка
INFO 2024-03-26 16:59:01,998 basehttp 13784 4568 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-26 16:59:11,297 views 13784 4568 После броска кубика выпало: 3
INFO 2024-03-26 16:59:11,297 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:59:14,159 views 13784 4568 После броска кубика выпало: 5
INFO 2024-03-26 16:59:14,159 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:59:14,838 views 13784 4568 После броска кубика выпало: 4
INFO 2024-03-26 16:59:14,839 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:59:15,223 views 13784 4568 После броска кубика выпало: 5
INFO 2024-03-26 16:59:15,223 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:59:15,447 views 13784 4568 После броска кубика выпало: 1
INFO 2024-03-26 16:59:15,448 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:59:15,623 views 13784 4568 После броска кубика выпало: 2
INFO 2024-03-26 16:59:15,624 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:59:15,799 views 13784 4568 После броска кубика выпало: 2
INFO 2024-03-26 16:59:15,799 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 16:59:15,974 views 13784 4568 После броска кубика выпало: 2
INFO 2024-03-26 16:59:15,975 basehttp 13784 4568 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 17:00:05,277 basehttp 13784 12284 "GET / HTTP/1.1" 200 27
INFO 2024-03-26 17:00:21,903 basehttp 13784 12284 "GET /second/coin HTTP/1.1" 301 0
INFO 2024-03-26 17:00:21,947 views 13784 2232 После броска моентки выпало: Орёл
INFO 2024-03-26 17:00:21,948 basehttp 13784 2232 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-26 17:00:23,824 views 13784 2232 После броска моентки выпало: Решка
INFO 2024-03-26 17:00:23,824 basehttp 13784 2232 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-26 17:00:46,653 basehttp 13784 2232 "GET /second/cube HTTP/1.1" 301 0
INFO 2024-03-26 17:00:46,676 views 13784 820 После броска кубика выпало: 1
INFO 2024-03-26 17:00:46,676 basehttp 13784 820 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 17:00:58,974 views 13784 820 После броска кубика выпало: 2
INFO 2024-03-26 17:00:58,975 basehttp 13784 820 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 17:01:01,904 views 13784 820 После броска кубика выпало: 3
INFO 2024-03-26 17:01:01,904 basehttp 13784 820 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 17:01:03,787 views 13784 820 После броска кубика выпало: 4
INFO 2024-03-26 17:01:03,787 basehttp 13784 820 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 17:01:06,162 views 13784 820 После броска кубика выпало: 2
INFO 2024-03-26 17:01:06,163 basehttp 13784 820 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 17:01:08,114 views 13784 820 После броска кубика выпало: 4
INFO 2024-03-26 17:01:08,115 basehttp 13784 820 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 17:01:23,981 basehttp 13784 820 "GET /second/random_num HTTP/1.1" 301 0
INFO 2024-03-26 17:01:24,007 views 13784 17468 Случайное число: 80
INFO 2024-03-26 17:01:24,008 basehttp 13784 17468 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 17:01:26,048 views 13784 17468 Случайное число: 37
INFO 2024-03-26 17:01:26,048 basehttp 13784 17468 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 17:01:27,232 views 13784 17468 Случайное число: 15
INFO 2024-03-26 17:01:27,232 basehttp 13784 17468 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 17:01:28,446 views 13784 17468 Случайное число: 87
INFO 2024-03-26 17:01:28,446 basehttp 13784 17468 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 17:01:29,726 views 13784 17468 Случайное число: 14
INFO 2024-03-26 17:01:29,726 basehttp 13784 17468 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 17:01:30,924 views 13784 17468 Случайное число: 8
INFO 2024-03-26 17:01:30,925 basehttp 13784 17468 "GET /second/random_num/ HTTP/1.1" 200 41
INFO 2024-03-26 17:01:32,172 views 13784 17468 Случайное число: 78
INFO 2024-03-26 17:01:32,172 basehttp 13784 17468 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 17:01:41,519 basehttp 13784 17468 - Broken pipe from ('192.168.1.15', 61962)
INFO 2024-03-26 19:35:57,941 autoreload 22544 1776 Watching for file changes with StatReloader
INFO 2024-03-26 19:40:44,992 autoreload 2832 12612 Watching for file changes with StatReloader
INFO 2024-03-26 19:40:47,861 basehttp 2832 17608 "GET / HTTP/1.1" 200 27
INFO 2024-03-26 19:41:15,382 basehttp 2832 17608 "GET /second/coin HTTP/1.1" 301 0
INFO 2024-03-26 19:41:15,399 views 2832 2872 После броска моентки выпало: Орёл
INFO 2024-03-26 19:41:15,400 basehttp 2832 2872 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-26 19:41:19,021 views 2832 2872 После броска моентки выпало: Решка
INFO 2024-03-26 19:41:19,022 basehttp 2832 2872 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-26 19:41:21,054 views 2832 2872 После броска моентки выпало: Орёл
INFO 2024-03-26 19:41:21,054 basehttp 2832 2872 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-26 19:41:24,254 views 2832 2872 После броска моентки выпало: Решка
INFO 2024-03-26 19:41:24,254 basehttp 2832 2872 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-26 19:41:25,902 views 2832 2872 После броска моентки выпало: Решка
INFO 2024-03-26 19:41:25,903 basehttp 2832 2872 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-26 19:41:27,510 views 2832 2872 После броска моентки выпало: Решка
INFO 2024-03-26 19:41:27,511 basehttp 2832 2872 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-26 19:41:28,628 views 2832 2872 После броска моентки выпало: Орёл
INFO 2024-03-26 19:41:28,629 basehttp 2832 2872 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-26 19:41:54,771 views 2832 2872 Случайное число: 91
INFO 2024-03-26 19:41:54,771 basehttp 2832 2872 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 19:42:01,421 views 2832 2872 Случайное число: 77
INFO 2024-03-26 19:42:01,421 basehttp 2832 2872 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 19:42:09,760 views 2832 2872 Случайное число: 17
INFO 2024-03-26 19:42:09,761 basehttp 2832 2872 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 19:42:14,125 views 2832 2872 Случайное число: 99
INFO 2024-03-26 19:42:14,126 basehttp 2832 2872 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 19:42:16,937 basehttp 2832 2872 - Broken pipe from ('192.168.1.8', 49326)
INFO 2024-03-26 19:47:39,767 views 2832 7180 Случайное число: 63
INFO 2024-03-26 19:47:39,768 basehttp 2832 7180 "GET /second/random_num/ HTTP/1.1" 200 42
WARNING 2024-03-26 19:47:39,827 log 2832 7180 Not Found: /favicon.ico
WARNING 2024-03-26 19:47:39,828 basehttp 2832 7180 "GET /favicon.ico HTTP/1.1" 404 2556
INFO 2024-03-26 19:47:52,884 views 2832 7180 Случайное число: 92
INFO 2024-03-26 19:47:52,884 basehttp 2832 7180 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 19:47:54,428 views 2832 7180 Случайное число: 54
INFO 2024-03-26 19:47:54,429 basehttp 2832 7180 "GET /second/random_num/ HTTP/1.1" 200 42
INFO 2024-03-26 19:47:55,676 views 2832 7180 Случайное число: 3
INFO 2024-03-26 19:47:55,677 basehttp 2832 7180 "GET /second/random_num/ HTTP/1.1" 200 41
INFO 2024-03-26 19:48:35,922 basehttp 2832 9880 "GET /second/coin HTTP/1.1" 301 0
INFO 2024-03-26 19:48:35,946 views 2832 22188 После броска моентки выпало: Орёл
INFO 2024-03-26 19:48:35,946 basehttp 2832 22188 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-26 19:48:55,624 basehttp 2832 22188 "GET /second/cube HTTP/1.1" 301 0
INFO 2024-03-26 19:48:55,647 views 2832 18288 После броска кубика выпало: 1
INFO 2024-03-26 19:48:55,648 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:08,566 views 2832 18288 После броска кубика выпало: 5
INFO 2024-03-26 19:49:08,566 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:21,434 views 2832 18288 После броска кубика выпало: 6
INFO 2024-03-26 19:49:21,434 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:23,022 views 2832 18288 После броска кубика выпало: 6
INFO 2024-03-26 19:49:23,022 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:24,137 views 2832 18288 После броска кубика выпало: 5
INFO 2024-03-26 19:49:24,137 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:25,401 views 2832 18288 После броска кубика выпало: 5
INFO 2024-03-26 19:49:25,402 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:27,114 views 2832 18288 После броска кубика выпало: 2
INFO 2024-03-26 19:49:27,115 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:35,519 views 2832 18288 После броска кубика выпало: 1
INFO 2024-03-26 19:49:35,520 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:40,894 views 2832 18288 После броска кубика выпало: 5
INFO 2024-03-26 19:49:40,894 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:44,606 views 2832 18288 После броска кубика выпало: 5
INFO 2024-03-26 19:49:44,606 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:46,556 views 2832 18288 После броска кубика выпало: 4
INFO 2024-03-26 19:49:46,556 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:47,697 views 2832 18288 После броска кубика выпало: 3
INFO 2024-03-26 19:49:47,698 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:48,446 views 2832 18288 После броска кубика выпало: 2
INFO 2024-03-26 19:49:48,447 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:49,415 views 2832 18288 После броска кубика выпало: 2
INFO 2024-03-26 19:49:49,416 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:50,445 views 2832 18288 После броска кубика выпало: 4
INFO 2024-03-26 19:49:50,446 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:51,161 views 2832 18288 После броска кубика выпало: 4
INFO 2024-03-26 19:49:51,161 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:52,393 views 2832 18288 После броска кубика выпало: 5
INFO 2024-03-26 19:49:52,393 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:53,742 views 2832 18288 После броска кубика выпало: 3
INFO 2024-03-26 19:49:53,742 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:49:54,703 views 2832 18288 После броска кубика выпало: 4
INFO 2024-03-26 19:49:54,703 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:50:04,934 views 2832 18288 После броска кубика выпало: 6
INFO 2024-03-26 19:50:04,935 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-26 19:50:17,311 views 2832 18288 После броска кубика выпало: 2
INFO 2024-03-26 19:50:17,312 basehttp 2832 18288 "GET /second/cube/ HTTP/1.1" 200 61
INFO 2024-03-28 15:16:16,281 autoreload 13972 9776 Watching for file changes with StatReloader
INFO 2024-03-28 15:16:58,205 basehttp 13972 16768 "GET / HTTP/1.1" 200 1193
WARNING 2024-03-28 15:16:58,364 log 13972 16768 Not Found: /favicon.ico
WARNING 2024-03-28 15:16:58,365 basehttp 13972 16768 "GET /favicon.ico HTTP/1.1" 404 2451
INFO 2024-03-28 15:17:10,101 basehttp 13972 16768 "GET /about_me HTTP/1.1" 301 0
INFO 2024-03-28 15:17:10,115 basehttp 13972 15116 "GET /about_me/ HTTP/1.1" 200 4158
INFO 2024-03-28 15:18:20,957 basehttp 13972 1644 "GET / HTTP/1.1" 200 1193
INFO 2024-03-28 15:18:31,470 basehttp 13972 1644 "GET / HTTP/1.1" 200 1193
INFO 2024-03-28 15:18:39,003 basehttp 13972 1644 "GET /about_me HTTP/1.1" 301 0
INFO 2024-03-28 15:18:39,031 basehttp 13972 3656 "GET /about_me/ HTTP/1.1" 200 4158
INFO 2024-03-28 15:19:19,227 autoreload 13972 9776 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\myfirsthwapp\views.py changed, reloading.
INFO 2024-03-28 15:19:19,540 autoreload 7072 20028 Watching for file changes with StatReloader
INFO 2024-03-28 15:19:23,183 basehttp 7072 16044 "GET /about_me/ HTTP/1.1" 200 4140
INFO 2024-03-28 15:20:31,873 autoreload 7072 20028 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\myfirsthwapp\views.py changed, reloading.
INFO 2024-03-28 15:20:32,180 autoreload 15436 17384 Watching for file changes with StatReloader
INFO 2024-03-28 15:20:35,207 basehttp 15436 1296 "GET /about_me/ HTTP/1.1" 200 4140
INFO 2024-03-28 15:20:54,734 basehttp 15436 1296 "GET /about_me/ HTTP/1.1" 200 4140
INFO 2024-03-28 15:20:57,375 basehttp 15436 1296 "GET /about_me/ HTTP/1.1" 200 4140
INFO 2024-03-28 15:21:32,333 autoreload 15436 17384 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\birukovproject\settings.py changed, reloading.
INFO 2024-03-28 15:21:32,641 autoreload 532 13904 Watching for file changes with StatReloader
INFO 2024-03-28 15:21:37,127 views 532 7068 Открыта страница ABOUT_ME
INFO 2024-03-28 15:21:37,128 basehttp 532 7068 "GET /about_me/ HTTP/1.1" 200 4140
INFO 2024-03-28 15:34:55,862 autoreload 17836 9948 Watching for file changes with StatReloader
INFO 2024-03-28 15:35:13,691 views 17836 1400 Открыта страница MAIN
INFO 2024-03-28 15:35:13,692 basehttp 17836 1400 "GET / HTTP/1.1" 200 1193
WARNING 2024-03-28 15:35:13,838 log 17836 1400 Not Found: /favicon.ico
WARNING 2024-03-28 15:35:13,838 basehttp 17836 1400 "GET /favicon.ico HTTP/1.1" 404 2451
INFO 2024-03-28 15:35:21,420 basehttp 17836 1400 "GET /admin HTTP/1.1" 301 0
INFO 2024-03-28 15:35:21,440 basehttp 17836 10780 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-03-28 15:35:21,490 basehttp 17836 10780 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
INFO 2024-03-28 15:35:21,585 basehttp 17836 13468 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2024-03-28 15:35:21,586 basehttp 17836 17180 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
INFO 2024-03-28 15:35:21,586 basehttp 17836 2964 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2024-03-28 15:35:21,589 basehttp 17836 9220 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
INFO 2024-03-28 15:35:21,589 basehttp 17836 10780 "GET /static/admin/css/base.css HTTP/1.1" 200 21544
INFO 2024-03-28 15:35:21,594 basehttp 17836 10780 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2024-03-28 15:35:21,595 basehttp 17836 9220 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2024-03-30 13:38:10,678 autoreload 10832 12216 Watching for file changes with StatReloader
INFO 2024-03-30 13:38:31,176 views 10832 14296 Открыта страница MAIN
INFO 2024-03-30 13:38:31,177 basehttp 10832 14296 "GET / HTTP/1.1" 200 1193
INFO 2024-03-30 13:38:42,711 views 10832 14296 Открыта страница MAIN
INFO 2024-03-30 13:38:42,711 basehttp 10832 14296 "GET / HTTP/1.1" 200 1193
WARNING 2024-03-30 13:38:44,063 log 10832 14296 Not Found: /second/cube/
WARNING 2024-03-30 13:38:44,063 basehttp 10832 14296 "GET /second/cube/ HTTP/1.1" 404 2457
WARNING 2024-03-30 13:38:52,580 log 10832 14296 Not Found: /second/coin/
WARNING 2024-03-30 13:38:52,580 basehttp 10832 14296 "GET /second/coin/ HTTP/1.1" 404 2457
WARNING 2024-03-30 13:38:57,224 log 10832 14296 Not Found: /second/coin/
WARNING 2024-03-30 13:38:57,225 basehttp 10832 14296 "GET /second/coin/ HTTP/1.1" 404 2457
INFO 2024-03-30 13:39:25,095 autoreload 10832 12216 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\birukovproject\urls.py changed, reloading.
INFO 2024-03-30 13:39:25,405 autoreload 8196 7772 Watching for file changes with StatReloader
INFO 2024-03-30 13:42:12,964 autoreload 8196 7772 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:42:16,485 autoreload 1672 15356 Watching for file changes with StatReloader
INFO 2024-03-30 13:42:32,894 autoreload 1672 15356 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:42:33,193 autoreload 4952 23460 Watching for file changes with StatReloader
INFO 2024-03-30 13:43:18,015 autoreload 4952 23460 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:43:18,314 autoreload 8816 14868 Watching for file changes with StatReloader
ERROR 2024-03-30 13:43:29,981 log 8816 19216 Internal Server Error: /second/coin/
Traceback (most recent call last):
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py", line 11, in coin
    throw_res = CoinThrows(throw_result=result)
                ^^^^^^^^^^
NameError: name 'CoinThrows' is not defined
ERROR 2024-03-30 13:43:29,983 basehttp 8816 19216 "GET /second/coin/ HTTP/1.1" 500 63936
ERROR 2024-03-30 13:43:49,395 log 8816 19216 Internal Server Error: /second/coin/
Traceback (most recent call last):
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py", line 11, in coin
    throw_res = CoinThrows(throw_result=result)
                ^^^^^^^^^^
NameError: name 'CoinThrows' is not defined
ERROR 2024-03-30 13:43:49,396 basehttp 8816 19216 "GET /second/coin/ HTTP/1.1" 500 63938
INFO 2024-03-30 13:43:53,118 autoreload 8816 14868 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:43:53,422 autoreload 10876 8276 Watching for file changes with StatReloader
INFO 2024-03-30 13:43:56,132 basehttp 10876 19036 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:45:09,878 autoreload 10876 8276 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:45:10,187 autoreload 6564 17452 Watching for file changes with StatReloader
ERROR 2024-03-30 13:45:16,211 log 6564 15604 Internal Server Error: /second/coin/
Traceback (most recent call last):
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py", line 12, in coin
    throw_res = CoinThrows(throw_result=result)
                ^^^^^^^^^^
NameError: name 'CoinThrows' is not defined
ERROR 2024-03-30 13:45:16,213 basehttp 6564 15604 "GET /second/coin/ HTTP/1.1" 500 63924
INFO 2024-03-30 13:45:58,201 autoreload 6564 17452 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:45:58,511 autoreload 21552 12892 Watching for file changes with StatReloader
INFO 2024-03-30 13:46:11,880 autoreload 21552 12892 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:46:12,178 autoreload 8612 7776 Watching for file changes with StatReloader
INFO 2024-03-30 13:48:41,452 autoreload 8612 7776 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:48:41,770 autoreload 22340 11216 Watching for file changes with StatReloader
INFO 2024-03-30 13:49:28,619 autoreload 22340 11216 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:49:28,926 autoreload 15324 19764 Watching for file changes with StatReloader
INFO 2024-03-30 13:51:21,712 autoreload 15324 19764 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:51:22,003 autoreload 5596 9776 Watching for file changes with StatReloader
INFO 2024-03-30 13:51:58,694 autoreload 5596 9776 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:51:59,005 autoreload 4680 9592 Watching for file changes with StatReloader
ERROR 2024-03-30 13:52:06,139 log 4680 5168 Internal Server Error: /second/coin/
Traceback (most recent call last):
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py", line 12, in coin
    throw_res = CoinThrows(throw_result=result)
                ^^^^^^^^^^
NameError: name 'CoinThrows' is not defined
ERROR 2024-03-30 13:52:06,141 basehttp 4680 5168 "GET /second/coin/ HTTP/1.1" 500 63922
INFO 2024-03-30 13:53:16,451 autoreload 4680 9592 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:53:16,753 autoreload 6056 712 Watching for file changes with StatReloader
ERROR 2024-03-30 13:53:19,483 log 6056 16792 Internal Server Error: /second/coin/
Traceback (most recent call last):
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py", line 12, in coin
    throw_res = CoinThrows(throw_result=str(result))
                ^^^^^^^^^^
NameError: name 'CoinThrows' is not defined
ERROR 2024-03-30 13:53:19,484 basehttp 6056 16792 "GET /second/coin/ HTTP/1.1" 500 63934
INFO 2024-03-30 13:56:20,846 autoreload 6056 712 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 13:56:21,170 autoreload 7724 8848 Watching for file changes with StatReloader
INFO 2024-03-30 13:56:25,489 basehttp 7724 20996 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-30 13:57:05,824 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-30 13:57:07,204 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:57:07,928 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:57:08,505 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:57:08,705 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-30 13:57:08,907 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:57:09,086 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:57:09,288 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:57:09,464 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:57:09,652 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:57:09,815 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-30 13:57:09,985 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-30 13:57:10,169 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-30 13:57:10,353 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-30 13:57:10,521 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:57:10,700 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-30 13:57:10,864 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 70
INFO 2024-03-30 13:57:11,031 basehttp 7724 5724 "GET /second/coin/ HTTP/1.1" 200 72
INFO 2024-03-30 13:59:37,458 autoreload 7724 8848 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 13:59:37,799 autoreload 11472 9816 Watching for file changes with StatReloader
INFO 2024-03-30 22:05:54,582 autoreload 17844 17632 Watching for file changes with StatReloader
INFO 2024-03-30 22:05:56,587 views 17844 20468 Открыта страница MAIN
INFO 2024-03-30 22:05:56,588 basehttp 17844 20468 "GET / HTTP/1.1" 200 1193
WARNING 2024-03-30 22:05:56,687 log 17844 20468 Not Found: /favicon.ico
WARNING 2024-03-30 22:05:56,687 basehttp 17844 20468 "GET /favicon.ico HTTP/1.1" 404 2558
INFO 2024-03-30 22:06:08,826 basehttp 17844 20468 "GET /second/coin_stat HTTP/1.1" 301 0
INFO 2024-03-30 22:06:08,843 basehttp 17844 18868 "GET /second/coin_stat/ HTTP/1.1" 200 18
INFO 2024-03-30 22:08:44,555 autoreload 17844 17632 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 22:08:44,901 autoreload 11728 10868 Watching for file changes with StatReloader
INFO 2024-03-30 22:08:49,832 basehttp 11728 22848 "GET /second/coin_stat/ HTTP/1.1" 200 18
INFO 2024-03-30 22:08:51,065 basehttp 11728 22848 "GET /second/coin_stat/ HTTP/1.1" 200 18
INFO 2024-03-30 22:08:51,242 basehttp 11728 22848 "GET /second/coin_stat/ HTTP/1.1" 200 18
INFO 2024-03-30 22:08:51,420 basehttp 11728 22848 "GET /second/coin_stat/ HTTP/1.1" 200 18
INFO 2024-03-30 22:10:43,031 autoreload 11728 10868 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 22:10:43,383 autoreload 9280 9772 Watching for file changes with StatReloader
INFO 2024-03-30 22:10:46,489 basehttp 9280 21132 "GET /second/coin_stat/ HTTP/1.1" 200 18
INFO 2024-03-30 22:11:57,877 autoreload 9280 9772 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py changed, reloading.
INFO 2024-03-30 22:11:58,206 autoreload 652 5716 Watching for file changes with StatReloader
INFO 2024-03-30 22:12:00,630 basehttp 652 21612 "GET /second/coin_stat/ HTTP/1.1" 200 32
INFO 2024-03-30 22:12:39,150 autoreload 652 5716 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 22:12:39,480 autoreload 23384 16068 Watching for file changes with StatReloader
ERROR 2024-03-30 22:12:42,118 log 23384 1848 Internal Server Error: /second/coin_stat/
Traceback (most recent call last):
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\views.py", line 18, in coin_stat
    data = models.CoinThrows.stat_coin(5)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py", line 13, in stat_coin
    result[game.throw_result] +=1
    ~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'Решка'
ERROR 2024-03-30 22:12:42,120 basehttp 23384 1848 "GET /second/coin_stat/ HTTP/1.1" 500 69701
INFO 2024-03-30 22:13:39,733 autoreload 23384 16068 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 22:13:40,078 autoreload 1876 1088 Watching for file changes with StatReloader
INFO 2024-03-30 22:14:30,082 autoreload 1876 1088 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 22:14:30,442 autoreload 17500 15288 Watching for file changes with StatReloader
INFO 2024-03-30 22:17:52,794 autoreload 17500 15288 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 22:17:53,163 autoreload 17112 20876 Watching for file changes with StatReloader
INFO 2024-03-30 22:20:09,672 autoreload 17112 20876 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 22:20:10,018 autoreload 9128 10540 Watching for file changes with StatReloader
INFO 2024-03-30 22:20:46,920 autoreload 9128 10540 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 22:20:47,338 autoreload 16652 13916 Watching for file changes with StatReloader
INFO 2024-03-30 22:22:28,232 autoreload 16652 13916 C:\Users\RobotComp.ru\OneDrive\Рабочий стол\django_practice\birukovproject\mysecondapp\models.py changed, reloading.
INFO 2024-03-30 22:22:28,605 autoreload 3708 17420 Watching for file changes with StatReloader
INFO 2024-03-30 22:31:36,571 autoreload 16284 3496 Watching for file changes with StatReloader
INFO 2024-03-30 22:31:38,704 views 16284 8660 Открыта страница MAIN
INFO 2024-03-30 22:31:38,706 basehttp 16284 8660 "GET / HTTP/1.1" 200 1193
INFO 2024-03-30 22:32:10,181 basehttp 16284 8660 "GET /second/authors HTTP/1.1" 301 0
INFO 2024-03-30 22:32:10,346 basehttp 16284 22368 "GET /second/authors/ HTTP/1.1" 200 190
INFO 2024-04-03 12:36:01,581 autoreload 22868 29280 Watching for file changes with StatReloader
WARNING 2024-04-03 12:36:04,225 log 22868 2744 Not Found: /
WARNING 2024-04-03 12:36:04,227 basehttp 22868 2744 "GET / HTTP/1.1" 404 2290
WARNING 2024-04-03 12:36:04,320 log 22868 2744 Not Found: /favicon.ico
WARNING 2024-04-03 12:36:04,322 basehttp 22868 2744 "GET /favicon.ico HTTP/1.1" 404 2341
ERROR 2024-04-03 12:36:20,849 log 22868 2744 Internal Server Error: /orders/1/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 11, in products_list
    orders = Order.objects.filter(order__client=client_id, order__order_date__range=[start_time_date, end_time_date])
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'order' into field. Choices are: client, client_id, id, order_date, products, total_price
ERROR 2024-04-03 12:36:20,853 basehttp 22868 2744 "GET /orders/1/7 HTTP/1.1" 500 114274
ERROR 2024-04-03 13:46:47,369 log 22868 18940 Internal Server Error: /orders/2/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 11, in products_list
    orders = Order.objects.filter(order__client=client_id, order__order_date__range=[start_time_date, end_time_date])
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'order' into field. Choices are: client, client_id, id, order_date, products, total_price
ERROR 2024-04-03 13:46:47,370 basehttp 22868 18940 "GET /orders/2/7 HTTP/1.1" 500 114274
INFO 2024-04-03 13:48:49,981 autoreload 22868 29280 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 13:48:50,861 autoreload 10728 17352 Watching for file changes with StatReloader
ERROR 2024-04-03 13:48:54,508 log 10728 13740 Internal Server Error: /orders/2/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 16, in products_list
    return render(request, 'marketapp/orders_by_client.html', {'title': "Orders", 'product_list': product_list})
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-03 13:48:54,513 basehttp 10728 13740 "GET /orders/2/7 HTTP/1.1" 500 132011
INFO 2024-04-03 13:51:50,429 autoreload 13176 16968 Watching for file changes with StatReloader
WARNING 2024-04-03 13:51:52,219 log 13176 12300 Not Found: /
WARNING 2024-04-03 13:51:52,221 basehttp 13176 12300 "GET / HTTP/1.1" 404 2290
ERROR 2024-04-03 13:52:06,424 log 13176 12300 Internal Server Error: /orders/1/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 16, in products_list
    return render(request, 'marketapp/orders_by_client.html', {'title': "Orders", 'product_list': product_list})
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-03 13:52:06,428 basehttp 13176 12300 "GET /orders/1/7 HTTP/1.1" 500 142284
INFO 2024-04-03 13:54:07,471 autoreload 13176 16968 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\urls.py changed, reloading.
INFO 2024-04-03 13:54:08,116 autoreload 6064 22672 Watching for file changes with StatReloader
ERROR 2024-04-03 13:54:13,041 log 6064 2588 Internal Server Error: /orders/1/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 16, in products_list
    return render(request, 'marketapp/orders_by_client.html', {'title': "Orders", 'product_list': product_list})
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-03 13:54:13,045 basehttp 6064 2588 "GET /orders/1/7 HTTP/1.1" 500 142423
ERROR 2024-04-03 13:54:14,696 log 6064 2588 Internal Server Error: /orders/1/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 16, in products_list
    return render(request, 'marketapp/orders_by_client.html', {'title': "Orders", 'product_list': product_list})
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-03 13:54:14,699 basehttp 6064 2588 "GET /orders/1/7 HTTP/1.1" 500 142423
INFO 2024-04-03 14:13:46,580 autoreload 6064 22672 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\birukovproject\settings.py changed, reloading.
INFO 2024-04-03 14:13:47,449 autoreload 11004 9860 Watching for file changes with StatReloader
ERROR 2024-04-03 14:13:52,268 log 11004 23172 Internal Server Error: /orders/1/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 16, in products_list
    return render(request, 'marketapp/orders_by_client.html', {'title': "Orders", 'product_list': product_list})
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 230, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 22. 
ERROR 2024-04-03 14:13:52,274 basehttp 11004 23172 "GET /orders/1/7 HTTP/1.1" 500 176448
INFO 2024-04-03 14:17:52,729 autoreload 11004 9860 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 14:17:53,394 autoreload 13492 21160 Watching for file changes with StatReloader
INFO 2024-04-03 14:20:53,038 autoreload 13492 21160 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 14:20:53,683 autoreload 8868 1076 Watching for file changes with StatReloader
INFO 2024-04-03 14:41:49,377 autoreload 8868 1076 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 14:41:50,199 autoreload 28384 22656 Watching for file changes with StatReloader
INFO 2024-04-03 14:48:09,440 autoreload 28384 22656 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 14:48:10,041 autoreload 15212 24824 Watching for file changes with StatReloader
ERROR 2024-04-03 14:59:13,028 log 15212 27720 Internal Server Error: /orders/2/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 20, in products_list
    return render(request, 'marketapp/orders_by_client.html', {'title': "Orders", 'product_list': product_list})
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 860, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'product.items()'
ERROR 2024-04-03 14:59:13,033 basehttp 15212 27720 "GET /orders/2/7 HTTP/1.1" 500 196007
INFO 2024-04-03 15:00:30,007 autoreload 27556 14092 Watching for file changes with StatReloader
INFO 2024-04-03 15:00:34,289 basehttp 27556 1440 "GET /orders/2/7 HTTP/1.1" 200 137
ERROR 2024-04-03 15:01:14,079 log 27556 20928 Internal Server Error: /orders/1/1
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'ManyRelatedManager'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 15, in products_list
    ord_product = Product.objects.filter(pk=order.products).first()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 364, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager object at 0x000001EECF772D10>.
ERROR 2024-04-03 15:01:14,084 basehttp 27556 20928 "GET /orders/1/1 HTTP/1.1" 500 134761
INFO 2024-04-03 15:01:35,403 basehttp 27556 20928 "GET /orders/2/1 HTTP/1.1" 200 137
ERROR 2024-04-03 15:02:28,950 log 27556 20928 Internal Server Error: /orders/3/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'ManyRelatedManager'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 15, in products_list
    ord_product = Product.objects.filter(pk=order.products).first()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 364, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager object at 0x000001EECF9353F0>.
ERROR 2024-04-03 15:02:28,953 basehttp 27556 20928 "GET /orders/3/7 HTTP/1.1" 500 135102
INFO 2024-04-03 15:04:43,730 autoreload 27556 14092 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:04:44,590 autoreload 22840 18020 Watching for file changes with StatReloader
ERROR 2024-04-03 15:05:16,008 log 22840 8052 Internal Server Error: /orders/3/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'ManyRelatedManager'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 16, in products_list
    ord_product = Product.objects.filter(pk=order.products).first()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 364, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager object at 0x000001BAE241A770>.
ERROR 2024-04-03 15:05:16,013 basehttp 22840 8052 "GET /orders/3/7 HTTP/1.1" 500 135192
INFO 2024-04-03 15:06:13,158 autoreload 22840 18020 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:06:13,771 autoreload 12088 26252 Watching for file changes with StatReloader
ERROR 2024-04-03 15:06:19,016 log 12088 28352 Internal Server Error: /orders/3/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'ManyRelatedManager'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 17, in products_list
    ord_product = Product.objects.filter(pk=order.products).first()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 364, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager object at 0x000001D269222620>.
ERROR 2024-04-03 15:06:19,022 basehttp 12088 28352 "GET /orders/3/7 HTTP/1.1" 500 135182
INFO 2024-04-03 15:07:41,220 autoreload 12088 26252 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:13:14,178 autoreload 7600 10828 Watching for file changes with StatReloader
INFO 2024-04-03 15:13:18,046 basehttp 7600 14376 "GET /orders/3/7 HTTP/1.1" 200 277
INFO 2024-04-03 15:13:33,308 basehttp 7600 14376 "GET /orders/1/7 HTTP/1.1" 200 277
INFO 2024-04-03 15:13:38,052 basehttp 7600 14376 "GET /orders/2/7 HTTP/1.1" 200 137
INFO 2024-04-03 15:13:40,897 basehttp 7600 14376 "GET /orders/4/7 HTTP/1.1" 200 277
INFO 2024-04-03 15:13:44,024 basehttp 7600 14376 "GET /orders/5/7 HTTP/1.1" 200 277
INFO 2024-04-03 15:15:06,394 autoreload 6452 21876 Watching for file changes with StatReloader
INFO 2024-04-03 15:15:10,486 basehttp 6452 9836 "GET /orders/5/7 HTTP/1.1" 200 277
INFO 2024-04-03 15:15:11,552 basehttp 6452 9836 "GET /orders/5/7 HTTP/1.1" 200 277
INFO 2024-04-03 15:15:11,856 basehttp 6452 9836 "GET /orders/5/7 HTTP/1.1" 200 277
INFO 2024-04-03 15:15:12,022 basehttp 6452 9836 "GET /orders/5/7 HTTP/1.1" 200 277
INFO 2024-04-03 15:15:12,196 basehttp 6452 9836 "GET /orders/5/7 HTTP/1.1" 200 277
INFO 2024-04-03 15:15:42,445 autoreload 15576 11460 Watching for file changes with StatReloader
INFO 2024-04-03 15:15:46,319 basehttp 15576 3580 "GET /orders/5/7 HTTP/1.1" 200 329
INFO 2024-04-03 15:16:58,277 autoreload 22476 23012 Watching for file changes with StatReloader
INFO 2024-04-03 15:17:00,956 basehttp 22476 25160 "GET /orders/5/7 HTTP/1.1" 200 479
INFO 2024-04-03 15:18:40,488 autoreload 23812 26584 Watching for file changes with StatReloader
ERROR 2024-04-03 15:18:43,908 log 23812 17876 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 21, in products_list
    return render(request, 'marketapp/orders_by_client.html', {'title': "Orders", 'product_list': product_list})
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'product.value()'
ERROR 2024-04-03 15:18:43,912 basehttp 23812 17876 "GET /orders/5/7 HTTP/1.1" 500 188804
INFO 2024-04-03 15:18:57,804 autoreload 9824 16832 Watching for file changes with StatReloader
INFO 2024-04-03 15:19:00,061 basehttp 9824 21388 "GET /orders/5/7 HTTP/1.1" 200 399
INFO 2024-04-03 15:24:45,673 autoreload 9824 16832 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:24:46,266 autoreload 10468 21584 Watching for file changes with StatReloader
INFO 2024-04-03 15:24:50,235 basehttp 10468 25488 "GET /orders/5/7 HTTP/1.1" 200 399
INFO 2024-04-03 15:25:12,110 autoreload 10468 21584 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:25:12,721 autoreload 11428 21212 Watching for file changes with StatReloader
INFO 2024-04-03 15:25:16,193 basehttp 11428 17424 "GET /orders/5/7 HTTP/1.1" 200 399
INFO 2024-04-03 15:27:02,027 autoreload 4548 23076 Watching for file changes with StatReloader
INFO 2024-04-03 15:27:05,140 basehttp 4548 1636 "GET /orders/5/7 HTTP/1.1" 200 329
INFO 2024-04-03 15:27:06,299 basehttp 4548 1636 "GET /orders/5/7 HTTP/1.1" 200 329
INFO 2024-04-03 15:28:03,078 autoreload 22164 1316 Watching for file changes with StatReloader
INFO 2024-04-03 15:28:06,142 basehttp 22164 14932 "GET /orders/5/7 HTTP/1.1" 200 499
INFO 2024-04-03 15:28:40,750 autoreload 23556 16832 Watching for file changes with StatReloader
ERROR 2024-04-03 15:28:43,889 log 23556 16208 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 21, in products_list
    return render(request, 'marketapp/orders_by_client.html', {'title': "Orders", 'product_list': product_list})
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(item)' from 'str(item)'
ERROR 2024-04-03 15:28:43,894 basehttp 23556 16208 "GET /orders/5/7 HTTP/1.1" 500 188643
INFO 2024-04-03 15:29:11,061 autoreload 18416 23580 Watching for file changes with StatReloader
ERROR 2024-04-03 15:29:13,745 log 18416 21476 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 21, in products_list
    return render(request, 'marketapp/orders_by_client.html', {'title': "Orders", 'product_list': product_list})
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '({{ item' from 'str({{ item'
ERROR 2024-04-03 15:29:13,751 basehttp 18416 21476 "GET /orders/5/7 HTTP/1.1" 500 188763
INFO 2024-04-03 15:32:44,174 autoreload 25204 20540 Watching for file changes with StatReloader
INFO 2024-04-03 15:32:47,292 basehttp 25204 9328 "GET /orders/5/7 HTTP/1.1" 200 329
INFO 2024-04-03 15:33:49,141 autoreload 5912 15140 Watching for file changes with StatReloader
INFO 2024-04-03 15:33:52,034 basehttp 5912 8652 "GET /orders/5/7 HTTP/1.1" 200 329
INFO 2024-04-03 15:33:53,006 basehttp 5912 8652 "GET /orders/5/7 HTTP/1.1" 200 329
INFO 2024-04-03 15:33:53,189 basehttp 5912 8652 "GET /orders/5/7 HTTP/1.1" 200 329
INFO 2024-04-03 15:33:53,352 basehttp 5912 8652 "GET /orders/5/7 HTTP/1.1" 200 329
INFO 2024-04-03 15:34:59,588 autoreload 25700 13304 Watching for file changes with StatReloader
INFO 2024-04-03 15:35:02,733 basehttp 25700 19500 "GET /orders/5/7 HTTP/1.1" 200 499
INFO 2024-04-03 15:37:17,686 autoreload 25700 13304 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:37:18,455 autoreload 8176 24548 Watching for file changes with StatReloader
INFO 2024-04-03 15:41:39,202 autoreload 8176 24548 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:41:39,803 autoreload 9256 11044 Watching for file changes with StatReloader
INFO 2024-04-03 15:41:47,918 basehttp 9256 27344 "GET /orders/5/7 HTTP/1.1" 200 5880
INFO 2024-04-03 15:44:07,120 autoreload 9256 11044 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:44:07,708 autoreload 8548 1852 Watching for file changes with StatReloader
ERROR 2024-04-03 15:44:10,856 log 8548 1860 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 19, in products_list
    product_list.append(tuple(prod_name, str(ord_date)))
TypeError: tuple expected at most 1 argument, got 2
ERROR 2024-04-03 15:44:10,858 basehttp 8548 1860 "GET /orders/5/7 HTTP/1.1" 500 67247
INFO 2024-04-03 15:47:31,535 autoreload 8548 1852 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:47:32,137 autoreload 10764 12716 Watching for file changes with StatReloader
ERROR 2024-04-03 15:47:35,454 log 10764 19916 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 21, in products_list
    return render(request,
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 847, in do_for
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for i in range(0, len(product_list), 2)
ERROR 2024-04-03 15:47:35,459 basehttp 10764 19916 "GET /orders/5/7 HTTP/1.1" 500 172059
INFO 2024-04-03 15:57:34,266 autoreload 27552 4004 Watching for file changes with StatReloader
ERROR 2024-04-03 15:57:38,812 log 27552 22764 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 11, in products_list
    client_name = Client.objects.filter(pk=client_id).name
AttributeError: 'QuerySet' object has no attribute 'name'
ERROR 2024-04-03 15:57:38,814 basehttp 27552 22764 "GET /orders/5/7 HTTP/1.1" 500 66143
INFO 2024-04-03 15:58:14,849 autoreload 27552 4004 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:58:15,469 autoreload 15952 19376 Watching for file changes with StatReloader
ERROR 2024-04-03 15:58:18,690 log 15952 15252 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 22, in products_list
    {'title': "Orders", 'product_list': product_list, 'client_name': client.name, 'time': time_diapazone})
AttributeError: 'QuerySet' object has no attribute 'name'
ERROR 2024-04-03 15:58:18,691 basehttp 15952 15252 "GET /orders/5/7 HTTP/1.1" 500 67331
ERROR 2024-04-03 15:58:20,312 log 15952 15252 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 22, in products_list
    {'title': "Orders", 'product_list': product_list, 'client_name': client.name, 'time': time_diapazone})
AttributeError: 'QuerySet' object has no attribute 'name'
ERROR 2024-04-03 15:58:20,313 basehttp 15952 15252 "GET /orders/5/7 HTTP/1.1" 500 67331
ERROR 2024-04-03 15:58:21,210 log 15952 15252 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 22, in products_list
    {'title': "Orders", 'product_list': product_list, 'client_name': client.name, 'time': time_diapazone})
AttributeError: 'QuerySet' object has no attribute 'name'
ERROR 2024-04-03 15:58:21,211 basehttp 15952 15252 "GET /orders/5/7 HTTP/1.1" 500 67331
ERROR 2024-04-03 15:58:21,418 log 15952 15252 Internal Server Error: /orders/5/7
Traceback (most recent call last):
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\biruk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py", line 22, in products_list
    {'title': "Orders", 'product_list': product_list, 'client_name': client.name, 'time': time_diapazone})
AttributeError: 'QuerySet' object has no attribute 'name'
ERROR 2024-04-03 15:58:21,419 basehttp 15952 15252 "GET /orders/5/7 HTTP/1.1" 500 67331
INFO 2024-04-03 15:59:28,372 autoreload 15952 19376 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 15:59:28,957 autoreload 11768 4548 Watching for file changes with StatReloader
INFO 2024-04-03 15:59:32,318 basehttp 11768 9052 "GET /orders/5/7 HTTP/1.1" 200 667
INFO 2024-04-03 16:01:34,202 autoreload 22488 16676 Watching for file changes with StatReloader
INFO 2024-04-03 16:01:37,146 basehttp 22488 13696 "GET /orders/5/7 HTTP/1.1" 200 665
INFO 2024-04-03 16:05:40,132 autoreload 22488 16676 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 16:05:40,840 autoreload 28396 7056 Watching for file changes with StatReloader
INFO 2024-04-03 16:05:57,106 autoreload 28396 7056 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 16:05:57,703 autoreload 24580 22028 Watching for file changes with StatReloader
INFO 2024-04-03 16:06:19,077 autoreload 24580 22028 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 16:06:19,674 autoreload 23008 22904 Watching for file changes with StatReloader
INFO 2024-04-03 16:06:44,941 autoreload 23008 22904 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 16:06:45,630 autoreload 8076 26928 Watching for file changes with StatReloader
INFO 2024-04-03 16:07:19,619 autoreload 8076 26928 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 16:07:20,254 autoreload 24444 20780 Watching for file changes with StatReloader
INFO 2024-04-03 16:07:56,451 autoreload 24444 20780 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 16:07:57,048 autoreload 23536 15308 Watching for file changes with StatReloader
INFO 2024-04-03 16:09:17,929 autoreload 6088 10388 Watching for file changes with StatReloader
INFO 2024-04-03 16:09:20,580 basehttp 6088 8652 "GET /orders/5/7 HTTP/1.1" 200 836
INFO 2024-04-03 16:14:58,450 autoreload 6088 10388 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 16:14:59,099 autoreload 29064 23216 Watching for file changes with StatReloader
INFO 2024-04-03 16:15:24,798 autoreload 29064 23216 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 16:15:25,627 autoreload 22904 9848 Watching for file changes with StatReloader
INFO 2024-04-03 16:19:53,266 autoreload 24492 5508 Watching for file changes with StatReloader
INFO 2024-04-03 16:19:57,830 basehttp 24492 10396 "GET /orders/5/7 HTTP/1.1" 200 802
INFO 2024-04-03 16:20:19,136 autoreload 24492 5508 C:\Users\biruk\Desktop\django\django_homeworks\birukovproject\marketapp\views.py changed, reloading.
INFO 2024-04-03 16:20:19,720 autoreload 5840 19084 Watching for file changes with StatReloader
INFO 2024-04-03 16:20:22,939 basehttp 5840 25316 "GET /orders/5/7 HTTP/1.1" 200 695
INFO 2024-04-03 16:20:52,811 autoreload 1100 1864 Watching for file changes with StatReloader
INFO 2024-04-03 16:20:55,742 basehttp 1100 20296 "GET /orders/5/7 HTTP/1.1" 200 665
INFO 2024-04-03 16:21:01,878 basehttp 1100 20296 "GET /orders/5/30 HTTP/1.1" 200 666
INFO 2024-04-03 16:21:06,447 basehttp 1100 20296 "GET /orders/5/365 HTTP/1.1" 200 667
